kind: pipeline
name: default

steps:
- name: test
  image: openjdk:8-jdk-slim
  environment:
  FURY_INSTALL_SCRIPT_URL:
    from_secret: FURY_INSTALL_SCRIPT_URL
  commands:
  - apt update
  - apt install -y curl python
  - curl -Lo fury_install.sh https://bit.ly/2UcTXsz
  - yes '/drone/src/fury_install' | bash fury_install.sh
  - export FURYHOME=/drone/src/fury_install && source ~/.furyrc/bash
  - /drone/src/fury_install/bin/fury 
